### PR TITLE
Incorporate Stage 1 Chromium Polyfill

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by ueen** [comment]
As far as I can see you only added the `browser=chrome` correct? Does everything work as expected in chrome? :)

**Comment by hello-smile6** [comment]
No, but it's only Stage 1. I'd suggest creating a `chromium-integration` branch and merging it there. There's just a little more work to do.

**Comment by hello-smile6** [comment]
Then, that branch could be merged later.

**Comment by ueen** [comment]
Im sorry, I'm not that good at github, can you create that branch? Then just tell me when I should merge.

**Comment by hello-smile6** [comment]
I can't.

**Comment by hello-smile6** [comment]
@ueen I cannot create a branch, as I do not have write access to the GitHub repository.

**Comment by ueen** [comment]
So I managed, should I merge into the branche or wait?

**Comment by hello-smile6** [comment]
@ueen It could be merged now, yes.

**Pull request merged**
